name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configurar .Net
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: Baixar dependencias
      run: dotnet restore
      
    - name: Build
      run: dotnet build
      
    - name: Testes unitarios
      run: dotnet test
      
